// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PzemReader.Data;

#nullable disable

namespace PzemReader.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505044409_2_key")]
    partial class _2_key
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PzemReader.Models.EnergyDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Day")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EnergyKwh")
                        .HasColumnType("real");

                    b.Property<float>("MaxPower")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("EnergyDays");
                });

            modelBuilder.Entity("PzemReader.Models.EnergyHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("EnergyKwh")
                        .HasColumnType("real");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("MaxPower")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("EnergyHours");
                });

            modelBuilder.Entity("PzemReader.Models.EnergyMinute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("EnergyKwh")
                        .HasColumnType("real");

                    b.Property<float>("MaxPower")
                        .HasColumnType("real");

                    b.Property<DateTime>("Minute")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EnergyMinutes");
                });

            modelBuilder.Entity("PzemReader.Models.PzemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Current")
                        .HasColumnType("real");

                    b.Property<float>("Energy")
                        .HasColumnType("real");

                    b.Property<float>("Frequency")
                        .HasColumnType("real");

                    b.Property<float>("Power")
                        .HasColumnType("real");

                    b.Property<float>("PowerFactor")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Voltage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PzemDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
