version: "3.8"

services:
  postgres_db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pzemdb
    ports:
      - 5432:5432
    volumes:
      - D:\Database\postgres_data:/var/lib/postgresql/data
    networks:
      - docker_net
    restart: always

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    # volumes:
    # - D:\Database\postgres_data:/var/lib/postgresql/data
    networks:
      - docker_net
    restart: always

networks:
  docker_net: 
    name: docker_network
